### ISSUE TITLE
Files don't open after renaming their parent folder

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#212]
If you rename a folder (within Genio or from Tracker), non of its contained files can be opened anymore. Works again after a Genio restart.

This is the Terminal output when renaming a folder:

```
BMessage('NTCH') {
        opcode = int32(0x3 or 3)
        device = int32(0x9 or 9)
        from directory = int64(0x20596a or 2120042)
        to directory = int64(0x20596a or 2120042)
        node device = int32(0x9 or 9)
        node = int64(0x28fd05 or 2686213)
        from name = string("BApplication with window, menu", 31 bytes)
        name = string("BApplication with window and menu", 34 bytes)
        from path = string("/Source/Genio/data/templates/BApplication with window, menu", 60 bytes)
        path = string("/Source/Genio/data/templates/BApplication with window and menu", 63 bytes)
        watched_path = string("/Source/Genio", 14 bytes)
        be:observe_orig_what = int32(0x5f504d4e or 1599098190)
        be:observe_change_what = int32(0x5f504d4e or 1599098190)
}
```

This when trying to open a file in that folder:
```
{E} (MSG_PROJECT_MENU_OPEN_FILE) Invalid entry_ref for
[/Source/Genio/data/templates/BApplication with window, menu/App.cpp]

```
It's still trying to access the "from path" instead of the new "path" from the renaming message.

**Comment by jackburton79** [comment]
This happens because SourceItem uses the path instead of the entry_ref.
I tried to do as little changes as possible (in fix/pathrename branch) to keep the entry_ref instead, but it seems that this breaks much of the path monitoring stuff in ProjectFolderBrowser, since it uses GetProjectItemByPath() to get pointers to items, passing the OLD path, while my changes made SourceItem::Path() return the CURRENT path, instead.
Seems more work is needed in the path monitoring code.

**Comment by jackburton79** [comment]
After all it seems the node monitoring code is ok. Should be fixed in the fix/pathrename branch. Needs a bit more testing to see if It breaks something else
