### ISSUE TITLE
Splitview not movable 

### ISSUE THREAD

**Issue by jackburton79** [Genio-The-Haiku-IDE/Genio#221]
The main splitview (between editor and projects/sourceControlPanel is not movable.
Probably some layout issue

**Comment by humdingerb** [comment]
Don't ask me why it just worked before adding the 2nd tab with "Source control", but if you add

```
fRepositoryNotInitializedView->SetExplicitMinSize(BSize(50.0, B_SIZE_UNSET));
fRepositoryNotInitializedView->SetExplicitMaxSize(BSize(B_SIZE_UNLIMITED, B_SIZE_UNSET));
```

after you did the goup layout in SourceControlPanel::_InitRepositoryNotInitializedView(), it works.
I tried with "B_SIZE_UNSET" instead of the 50.0, but that didn't let me make the split narrower.
Not sure what value fits best. Maybe even "0" to mae it arbitraily small...
