### ISSUE TITLE
[RFE] Dark mode should affect ALL windows and panels

### ISSUE THREAD

**Issue by grexe** [Genio-The-Haiku-IDE/Genio#412]
I would really prefer to use Genio in dark mode, and the dark solarized scheme works really well.
However, the other panels, beside the editor, are still glaring white, killing my eyes.
Can you please apply dark mode to *all* of the UI consistently and not just the editor?

**Comment by grexe** [comment]
![genio-mixed-colorscheme](https://github.com/Genio-The-Haiku-IDE/Genio/assets/404952/44e5415b-13d3-4d3f-a949-f7a4e9f90924)

**Comment by jackburton79** [comment]
This one is not simple: we're using system widgets, so their color depends on your system colors. There is no way in Haiku to set custom colors only for a given application.
The Editor isn't a native component (it's using Scintilla) so we can customize it and stylize it.
What you could do (it's what I do) is set a dark color in Haiku Appearance so that the whole system uses this dark theme.

**Comment by grexe** [comment]
ok I see, I was suspecting something like that, so will follow your suggestion, thanks!
it's just that this looks a bit mixed and out of place, but this is something that has to be solved in Haiku later.

**Comment by nexus6-haiku** [comment]
If you want a better result you need the flat decorator and control look and tweaking the colours manually
